"""Add powers column to heroes table

Revision ID: 309a4ffb61af
Revises: 736113213a43
Create Date: 2025-08-23 04:10:37.137010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309a4ffb61af'
down_revision: Union[str, Sequence[str], None] = '736113213a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heroes', sa.Column('powers', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heroes', 'powers')
    # ### end Alembic commands ###
